<h1 class="text-center">Commande n°<?= $_GET['order'] ?></h1>

<nav>
    <a href="index.php">Retour à la liste des commandes</a>
</nav>

<header class="float-right">
    <h2><?= $customer['customerName'] ?></h2>
    <p><?= $customer['contactFirstName'] ?> <?= $customer['contactLastName'] ?></p>
    <p>
        <?= $customer['addressLine1'] ?><br>
        <?= $customer['city'] ?>
    </p>
</header>

<table class="table">
    <thead>
        <tr>
            <th>Nom du produit</th>
            <th>Quantité</th>
            <th>Prix unitaire</th>
            <th>Prix total</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($orderdetails as $detail): ?>
            <tr>
                <td><?= $detail['productName'] ?></td>
                <td><?= $detail['quantityOrdered'] ?></td>
                <td><?= number_format($detail['priceEach'], 2, ',', ' ') ?>€</td>
                <td><?= number_format($detail['total'], 2, ',', ' ') ?>€</td>
            </tr>
        <?php endforeach ?>
    </tbody>
    <tfoot>
        <tr>
            <th colspan="3">
                Total HT
            </th>
            <th><?= number_format($results['totalHT'], 2, ',', ' ') ?>€</th>
        </tr>
        <tr>
            <th colspan="3">
                Total TVA
            </th>
            <th><?= number_format($results['totalTVA'], 2, ',', ' ') ?>€</th>
        </tr>
        <tr>
            <th colspan="3">
                Total HT
            </th>
            <th><?= number_format($results['totalTTC'], 2, ',', ' ') ?>€</th>
        </tr>
    </tfoot>
</table>